export const slidedata = [
    {
        id:1,
        title:"albergo",
        image:"/About/logo-slider1.png"
    },
    {
        id:2,
        title:"esalto",
        image:"/About/logo-slider2.png"
    },
    {
        id:3,
        title:"iroute",
        image:"/About/logo-slider3.png"
    },
    {
        id:4,
        title:"forzaerp",
        image:"/About/logo-slider4.png"
    },
    {
        id:5,
        title:"softpulse",
        image:"/About/logo-slider5.png"
    },
    {
        id:6,
        title:"forzaretail",
        image:"/About/logo-slider6.png"
    },
    {
        id:7,
        title:"ichef",
        image:"/About/logo-slider7.png"
    },
   
    
]